baseurl = "/"
languageCode = "de-de"
languageLang = "de"
title = "kraftwerk.social"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[params]
images = ["img/og-image.jpg"]

theme = ["PaperMod"]
